//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Code/Inputs/NpcInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NpcInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NpcInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NpcInput"",
    ""maps"": [
        {
            ""name"": ""NPC"",
            ""id"": ""1246a617-add0-4944-a259-0c269625f000"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""cc4cdfbc-ee80-4883-b57b-f5b00384c051"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8df93276-a9c6-4357-8445-339e6d79c3d6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NPC
        m_NPC = asset.FindActionMap("NPC", throwIfNotFound: true);
        m_NPC_Interact = m_NPC.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NPC
    private readonly InputActionMap m_NPC;
    private INPCActions m_NPCActionsCallbackInterface;
    private readonly InputAction m_NPC_Interact;
    public struct NPCActions
    {
        private @NpcInput m_Wrapper;
        public NPCActions(@NpcInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_NPC_Interact;
        public InputActionMap Get() { return m_Wrapper.m_NPC; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NPCActions set) { return set.Get(); }
        public void SetCallbacks(INPCActions instance)
        {
            if (m_Wrapper.m_NPCActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_NPCActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_NPCActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_NPCActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_NPCActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public NPCActions @NPC => new NPCActions(this);
    public interface INPCActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
}
